## **ikinci deneme lllllllllllllllllll!!!!!!!!!!!!!!!!!!!!!**

### **giriş**

In [1]:
import numpy as np
c = 299_792_458.0

### **rec_init**

In [2]:
#   4208830.3061  2334850.2992  4171267.2489                  APPROX POSITION XYZ
rec_init = np.array([
    4208830.3061,
    2334850.2992,
    4171267.2489
])

### **sat_xyz_array**

In [3]:
from pathlib import Path

In [4]:
# başlangıç ile bitiş satırı arası verileri toplar, satırın tamamını girdi olarak yaz, boşluklar ile beraber kopyala
def get_data(file_path, start_line, end_line):
    data = []
    collecting = False

    with open(file_path, "r") as f:
        for line in f:
            if line.rstrip() == start_line:
                collecting = True

            if line.rstrip() == end_line:
                break

            if collecting:
                data.append(line.rstrip())

    return data

In [5]:
data_dir = Path("../data")
sp3_file = data_dir / "igs18074.sp3"

In [6]:
data = get_data(sp3_file,
               "*  2014  8 28 17 15  0.00000000",
               "*  2014  8 28 17 30  0.00000000")
data = data[1:]

In [7]:
data[:5]

['PG01  13476.921598 -10426.955243  20291.904644     20.349088  4  6  7 120',
 'PG02 -13550.313835 -15991.021351 -16281.321964    515.186695  7  5  5 122',
 'PG04   7308.999939 -21942.314164  12476.840846     -0.280439  6  9  4 131',
 'PG05 -18419.851511  -3796.077731 -18858.852840   -345.105473  3  6  4 110',
 'PG06  -7035.751316 -24544.047305  -7350.758926     -5.073708  6  8  7  84']

In [8]:
data[:1]

['PG01  13476.921598 -10426.955243  20291.904644     20.349088  4  6  7 120']

In [9]:
# uydu koordinat listesi sp3ten verilen epokta lındıktan sonra listeye kaydedildi.
# listeler iç içe sat_xyz_list[0] 0ıncı uydunu satırındaki bütün bilgileri içeren başka bir liste
sat_xyz_list = []
for i in range(len(data)):
    x = data[i].split()
    sat_xyz_list.append(x)

In [10]:
# uydu koordinatları metre biriminde float veri tipine çevrildi.
for i in range(len(sat_xyz_list)):
    sat_xyz_list[i][1] = float(sat_xyz_list[i][1])*1000
    sat_xyz_list[i][2] = float(sat_xyz_list[i][2])*1000
    sat_xyz_list[i][3] = float(sat_xyz_list[i][3])*1000

In [11]:
sat_xyz_list[0]

['PG01',
 13476921.598000001,
 -10426955.243,
 20291904.643999998,
 '20.349088',
 '4',
 '6',
 '7',
 '120']

In [12]:
satellites = ["PG19", "PG27", "PG11", "PG20", "PG22","PG14", "PG32", "PG01", "PG31"]
sat_xyz_list_filtered = []
for i in sat_xyz_list:
    if i[0] in satellites:
        print(i[0])
        x = i[1]
        y = i[2]
        z = i[3]
        sat_xyz_list_filtered.append([x,y,z,])
sat_xyz_array = np.array(sat_xyz_list_filtered)

PG01
PG11
PG14
PG19
PG20
PG22
PG27
PG31
PG32

In [13]:
sat_xyz_array

array([[ 13476921.598, -10426955.243,  20291904.644],
       [ 16469526.655,  -2836172.328,  20153200.739],
       [  7630518.742,  18517714.593,  17754617.164],
       [ 24070866.651,   7158793.606,   9150872.837],
       [ 21867317.358, -14785045.52 ,   2401922.252],
       [   232378.327,  17992583.515,  19708061.664],
       [ 23397361.903,  12532536.308,  -1720216.341],
       [  7150581.839,  23678014.313,  -9091109.009],
       [ 22686205.155,  -1860106.849,  13257342.82 ]])

### **P**

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("../data/satellites2.csv")
df # pandas csv okumak için

,Satellite,C1,P1,L1,D1,P2,L2,D2
0,G19,2.118906e+07,2.118905e+07,-2.342237e+07,-1624.826,2.118904e+07,-1.823279e+07,-1266.095
1,G27,2.252061e+07,2.252059e+07,-1.626506e+07,-3131.943,2.252059e+07,-1.266448e+07,-2440.473
2,G11,2.096043e+07,2.096043e+07,-2.023690e+07,2125.069,2.096042e+07,-1.575303e+07,1655.895
3,G20,2.459961e+07,2.459960e+07,-4.001554e+06,3287.044,2.459959e+07,-2.858091e+06,2561.330
4,G22,2.234385e+07,2.234385e+07,-1.900831e+07,-2218.107,2.234382e+07,-1.478600e+07,-1728.398
5,G14,2.137030e+07,2.137029e+07,-1.900141e+07,-529.566,2.137029e+07,-1.455393e+07,-412.656
6,G32,2.112843e+07,2.112842e+07,-1.989570e+07,1824.349,2.112841e+07,-1.548879e+07,1421.562
7,G01,2.255605e+07,2.255604e+07,-1.514390e+07,2922.988,2.255604e+07,-1.177665e+07,2277.661
8,G31,0.000000e+00,2.519183e+07,-8.747164e+04,3119.319,2.519183e+07,-3.090521e+03,2429.440

In [16]:
#df sıralandı yoksa uydu ve P listeleri sıralı eşleşmiyordu sıkıntı oldu
df = df.sort_values(
    by=df.columns[0],
    key=lambda col: col.str[1:].astype(int)
).reset_index(drop=True)

In [17]:
df

,Satellite,C1,P1,L1,D1,P2,L2,D2
0,G01,2.255605e+07,2.255604e+07,-1.514390e+07,2922.988,2.255604e+07,-1.177665e+07,2277.661
1,G11,2.096043e+07,2.096043e+07,-2.023690e+07,2125.069,2.096042e+07,-1.575303e+07,1655.895
2,G14,2.137030e+07,2.137029e+07,-1.900141e+07,-529.566,2.137029e+07,-1.455393e+07,-412.656
3,G19,2.118906e+07,2.118905e+07,-2.342237e+07,-1624.826,2.118904e+07,-1.823279e+07,-1266.095
4,G20,2.459961e+07,2.459960e+07,-4.001554e+06,3287.044,2.459959e+07,-2.858091e+06,2561.330
5,G22,2.234385e+07,2.234385e+07,-1.900831e+07,-2218.107,2.234382e+07,-1.478600e+07,-1728.398
6,G27,2.252061e+07,2.252059e+07,-1.626506e+07,-3131.943,2.252059e+07,-1.266448e+07,-2440.473
7,G31,0.000000e+00,2.519183e+07,-8.747164e+04,3119.319,2.519183e+07,-3.090521e+03,2429.440
8,G32,2.112843e+07,2.112842e+07,-1.989570e+07,1824.349,2.112841e+07,-1.548879e+07,1421.562

In [18]:
# csvden yine listeye dönüştür sat1 sat2 ...
for i in range(9):
    globals()[f"sat{i+1}"] = ([str(df.iloc[i, 0])] + [float(x) for x in df.iloc[i, 1:]])
    print(globals()[f"sat{i+1}"])

['G01', 22556048.986, 22556038.04462001, -15143902.884, 2922.988, 22556035.42729401, -11776649.861, 2277.661]
['G11', 20960433.392, 20960425.14970588, -20236898.563, 2125.069, 20960421.774224665, -15753030.25, 1655.895]
['G14', 21370295.018, 21370286.18971318, -19001406.309, -529.566, 21370288.72879227, -14553929.347, -412.656]
['G19', 21189058.919, 21189051.21103306, -23422371.335, -1624.826, 21189044.57144488, -18232789.099, -1266.095]
['G20', 24599610.601, 24599598.41016102, -4001554.056, 3287.044, 24599594.33452711, -2858090.765, 2561.33]
['G22', 22343853.992, 22343848.59559468, -19008308.324, -2218.107, 22343819.58930088, -14786004.908, -1728.398]
['G27', 22520607.109, 22520594.159697726, -16265062.308, -3131.943, 22520588.638844248, -12664483.164, -2440.473]
['G31', 0.0, 25191834.43034392, -87471.641, 3119.319, 25191831.90635393, -3090.521, 2429.44]
['G32', 21128427.864, 21128417.40142765, -19895704.4, 1824.349, 21128414.788728934, -15488787.194, 1421.562]

In [19]:
P1_corr = []
for i in range(9):
    P1 = globals()[f"sat{i+1}"][2]
    P1_corr.append(P1)

In [20]:
P1_corr

[22556038.04462001,
 20960425.14970588,
 21370286.18971318,
 21189051.21103306,
 24599598.41016102,
 22343848.59559468,
 22520594.159697726,
 25191834.43034392,
 21128417.40142765]

In [21]:
P2_corr = []
for i in range(9):
    P2 = globals()[f"sat{i+1}"][5]
    P2_corr.append(P2)

In [22]:
P2_corr

[22556035.42729401,
 20960421.774224665,
 21370288.72879227,
 21189044.57144488,
 24599594.33452711,
 22343819.58930088,
 22520588.638844248,
 25191831.90635393,
 21128414.788728934]

### **lsq fonksiyon**

In [23]:
# P ve sat_coords önceden geliyor
def spp_lsq(P, sat_coords, rec_init, max_iter=40, tol=1e-4): # max iterasyon ve tolerans default = 10, 0.001metre = 1milimetre
    n = len(P) # pseudo range sayısı 9du 8e düşürdük
    P = np.asarray(P, dtype=float) 
    sat_coords = np.asarray(sat_coords, dtype=float) # uydu koord.
    X_rec = np.asarray(rec_init, dtype=float).copy() # alıcı aprox koord.
    c_dt_rec = 0.0 # Alıcı saat hatasının mesafesel karşılığı [m] = 0 kabul ile başlıyoruz iterasyona

    for iteration in range(max_iter): # max iter 40
        A = np.zeros((n, 4)) 
        l = np.zeros(n)

        for i in range(n): # her pseudorange için
            d = sat_coords[i] - X_rec # geometrik mesafe xyz, X_rec güncel geliyor
            rho = np.linalg.norm(d) # geometrik mesafe vektör = uzunluk
            A[i, :3] = -d / rho # Tasarım matrisi
            A[i, 3] = 1.0
            l[i] = P[i] - rho - c_dt_rec # Ölçü farkı, c_dt_rec güncel geliyor
        print("ITERASYON ve A ve l : ",iteration,A,l)
        # LSQ çözümü
        dx, residuals, _, _ = np.linalg.lstsq(A, l) #dx, düzeltmeler
        print("dx ve residuals: ",dx, residuals)
        X_rec += dx[:3] # dx 0,1,2 elementlerini ekle X_rec için başlangıçta rec_initle aynı
        c_dt_rec += dx[3] # c_dt 3.element
        if np.linalg.norm(dx[:3]) < tol: #koord vektör uzunluk 1mmden kısa ise tamam
            break

    # Son çözümde tasarım matrisini ve kalıntıları yeniden hesapla
    A = np.zeros((n, 4))
    v = np.zeros(n)
    for i in range(n): # range(8) her bir uydu için son döngü, vleri bul
        d = sat_coords[i] - X_rec
        rho = np.linalg.norm(d)
        A[i, :3] = -d / rho
        A[i, 3] = 1.0
        v[i] = P[i] - rho - c_dt_rec
        
    Q = np.linalg.inv(A.T @ A) # DOP hesabı için kofaktör matrisi
    dt_rec = c_dt_rec / c # Alıcı saat hatası [s]
    return X_rec, dt_rec, Q, v

### **çıktılar p1 p2 için**

In [24]:
X_P1, dt_P1, Q_P1, v_P1 = spp_lsq(
    P=P1_corr,
    sat_coords=sat_xyz_array,
    rec_init=rec_init
)

print("P1 çözümü")
print("Alıcı koordinatları [m]:", X_P1)
print("Alıcı saat hatası [s]:", dt_P1)
print("Alıcı saat hatası [ns]:", dt_P1 * 1e9)
print("Kalıntılar [m]:", v_P1)

ITERASYON ve A ve l :  0 [[-0.41094783  0.56585937 -0.71479022  1.        ]
 [-0.58956126  0.24865102 -0.76849867  1.        ]
 [-0.15986747 -0.75609268 -0.63463867  1.        ]
 [-0.94413494 -0.22930445 -0.23670381  1.        ]
 [-0.71612055  0.69427858  0.07175384  1.        ]
 [ 0.17741259 -0.6985823  -0.69318652  1.        ]
 [-0.85227488 -0.45293886  0.26167523  1.        ]
 [-0.11627611 -0.84361309  0.52421067  1.        ]
 [-0.87930909  0.19963139 -0.43239199  1.        ]] [   3074.89304687  164119.03412554  -32994.94706503  151765.53520535
  -58941.27775311  -69735.68930579    6107.18643169 -107872.60763177
  114902.32027721]
dx ve residuals:  [-252971.16066962  -55932.25735854 -145894.2770018  -157717.68549021] [1.40393653e+10]
ITERASYON ve A ve l :  1 [[-0.41886149  0.55897133 -0.71561589  1.        ]
 [-0.59463434  0.24306291 -0.76637486  1.        ]
 [-0.17028128 -0.752495   -0.63620402  1.        ]
 [-0.94331977 -0.22884819 -0.24036707  1.        ]
 [-0.72247426  0.68828982  0.0654833   1.        ]
 [ 0.16540959 -0.69805406 -0.69667797  1.        ]
 [-0.85576451 -0.45133767  0.25290593  1.        ]
 [-0.12626577 -0.84576145  0.51840576  1.        ]
 [-0.87984717  0.1944283  -0.43366645  1.        ]] [-17058.13115902  73835.94432883 -51935.48214748  23132.68367363
 -34512.79978161  -9104.89107103 -39974.04026516  47977.58249042
  -2046.04631818]
dx ve residuals:  [-1467.98972948  -430.67438313  -395.92390764 -1996.11934461] [1.41410712e+10]
ITERASYON ve A ve l :  2 [[-0.41891395  0.55893622 -0.71561261  1.        ]
 [-0.59467381  0.24303006 -0.76635465  1.        ]
 [-0.17034278 -0.75248616 -0.63619802  1.        ]
 [-0.94331878 -0.22885145 -0.24036784  1.        ]
 [-0.72251196  0.68825196  0.06546538  1.        ]
 [ 0.16534192 -0.69806285 -0.69668523  1.        ]
 [-0.85577825 -0.4513298   0.25287347  1.        ]
 [-0.12632207 -0.84576696  0.51838306  1.        ]
 [-0.87985911  0.19439547 -0.43365694  1.        ]] [-15719.53640087  74760.36936432 -50765.3447225   23550.29304029
 -33254.9494019   -7442.47061324 -39328.43731713  49629.29942696
  -1429.51116454]
dx ve residuals:  [ 0.53981932 -0.18330148  1.11889018  0.54412208] [1.41410721e+10]
ITERASYON ve A ve l :  3 [[-0.41891395  0.55893624 -0.7156126   1.        ]
 [-0.59467382  0.24303007 -0.76635464  1.        ]
 [-0.17034276 -0.75248619 -0.63619798  1.        ]
 [-0.94331879 -0.22885146 -0.2403678   1.        ]
 [-0.72251195  0.68825196  0.06546542  1.        ]
 [ 0.16534195 -0.69806287 -0.6966852   1.        ]
 [-0.85577823 -0.45132981  0.25287352  1.        ]
 [-0.12632204 -0.84576694  0.51838309  1.        ]
 [-0.87985913  0.19439547 -0.43365691  1.        ]] [-15718.95123935  74761.04827312 -50765.22298639  23550.4851363
 -33255.05058906  -7442.4524318  -39328.88514068  49628.08845191
  -1429.05947421]
dx ve residuals:  [-0.00226653 -0.00026747 -0.00184546 -0.00172719] [1.41410721e+10]
ITERASYON ve A ve l :  4 [[-0.41891395  0.55893624 -0.7156126   1.        ]
 [-0.59467382  0.24303007 -0.76635464  1.        ]
 [-0.17034276 -0.75248619 -0.63619798  1.        ]
 [-0.94331879 -0.22885146 -0.2403678   1.        ]
 [-0.72251195  0.68825196  0.06546542  1.        ]
 [ 0.16534195 -0.69806287 -0.6966852   1.        ]
 [-0.85577823 -0.45132981  0.25287352  1.        ]
 [-0.12632204 -0.84576694  0.51838309  1.        ]
 [-0.87985913  0.19439547 -0.43365691  1.        ]] [-15718.95163278  74761.04730318 -50765.22302064  23550.48422062
 -33255.05019457  -7442.45180228 -39328.88500719  49628.09062322
  -1429.06048956]
dx ve residuals:  [3.45967718e-06 1.10223101e-07 3.48061238e-06 2.78801956e-06] [1.41410721e+10]
P1 çözümü
Alıcı koordinatları [m]: [3954391.69325715 2278487.18388948 4024978.16503876]
Alıcı saat hatası [s]: -0.0005327460987599049
Alıcı saat hatası [ns]: -532746.098759905
Kalıntılar [m]: [-15718.95163169  74761.04730509 -50765.22302055  23550.48422196
 -33255.05019516  -7442.45180314 -39328.88500785  49628.09061915
  -1429.06048782]

In [25]:
X_P2, dt_P2, Q_P2, v_P2 = spp_lsq(
    P=P2_corr,
    sat_coords=sat_xyz_array,
    rec_init=rec_init
)

print("P2 çözümü")
print("Alıcı koordinatları [m]:", X_P2)
print("Alıcı saat hatası [s]:", dt_P2)
print("Alıcı saat hatası [ns]:", dt_P2 * 1e9)
print("Kalıntılar [m]:", v_P2)

ITERASYON ve A ve l :  0 [[-0.41094783  0.56585937 -0.71479022  1.        ]
 [-0.58956126  0.24865102 -0.76849867  1.        ]
 [-0.15986747 -0.75609268 -0.63463867  1.        ]
 [-0.94413494 -0.22930445 -0.23670381  1.        ]
 [-0.71612055  0.69427858  0.07175384  1.        ]
 [ 0.17741259 -0.6985823  -0.69318652  1.        ]
 [-0.85227488 -0.45293886  0.26167523  1.        ]
 [-0.11627611 -0.84361309  0.52421067  1.        ]
 [-0.87930909  0.19963139 -0.43239199  1.        ]] [   3072.27572087  164115.65864433  -32992.40798594  151758.89561717
  -58945.35338702  -69764.69559959    6101.66557821 -107875.13162176
  114899.7075785 ]
dx ve residuals:  [-252979.38789379  -55930.56642224 -145891.38272715 -157726.68997991] [1.40392632e+10]
ITERASYON ve A ve l :  1 [[-0.4188618   0.55897135 -0.71561569  1.        ]
 [-0.59463464  0.24306295 -0.76637461  1.        ]
 [-0.17028167 -0.75249499 -0.63620394  1.        ]
 [-0.94331986 -0.22884804 -0.24036685  1.        ]
 [-0.72247438  0.68828969  0.0654834   1.        ]
 [ 0.16540925 -0.69805413 -0.69667798  1.        ]
 [-0.85576461 -0.45133746  0.25290598  1.        ]
 [-0.12626609 -0.84576134  0.51840585  1.        ]
 [-0.8798473   0.19442832 -0.43366618  1.        ]] [-17054.06406024  73838.48824112 -51922.22575238  23128.3703272
 -34515.16826492  -9120.33527232 -39977.56599202  47982.9538919
  -2045.96684411]
dx ve residuals:  [-1468.10602241  -430.67819928  -395.87646856 -1996.20197822] [1.41409728e+10]
ITERASYON ve A ve l :  2 [[-0.41891427  0.55893623 -0.71561241  1.        ]
 [-0.59467412  0.24303011 -0.76635439  1.        ]
 [-0.17034318 -0.75248614 -0.63619793  1.        ]
 [-0.94331887 -0.22885129 -0.24036763  1.        ]
 [-0.72251208  0.68825182  0.06546548  1.        ]
 [ 0.16534159 -0.69806291 -0.69668524  1.        ]
 [-0.85577835 -0.45132958  0.25287352  1.        ]
 [-0.12632239 -0.84576685  0.51838315  1.        ]
 [-0.87985924  0.19439549 -0.43365667  1.        ]] [-15715.39968603  74762.96370867 -50751.99873282  23545.96317149
 -33257.31994806  -7457.7830875  -39331.99368224  49634.7105643
  -1429.43013439]
dx ve residuals:  [ 0.53957881 -0.18328944  1.11910091  0.54406017] [1.41409736e+10]
ITERASYON ve A ve l :  3 [[-0.41891427  0.55893625 -0.71561239  1.        ]
 [-0.59467413  0.24303011 -0.76635439  1.        ]
 [-0.17034316 -0.75248617 -0.6361979   1.        ]
 [-0.94331888 -0.22885131 -0.24036758  1.        ]
 [-0.72251207  0.68825183  0.06546552  1.        ]
 [ 0.16534161 -0.69806294 -0.69668521  1.        ]
 [-0.85577833 -0.45132959  0.25287357  1.        ]
 [-0.12632237 -0.84576684  0.51838318  1.        ]
 [-0.87985926  0.19439549 -0.43365664  1.        ]] [-15714.81441934  74763.6426948  -50751.87683252  23546.15515577
 -33257.42126924  -7457.76464899 -39332.44169752  49633.49952181
  -1428.97850496]
dx ve residuals:  [-0.00226681 -0.00026732 -0.0018455  -0.00172732] [1.41409736e+10]
ITERASYON ve A ve l :  4 [[-0.41891427  0.55893625 -0.71561239  1.        ]
 [-0.59467413  0.24303011 -0.76635439  1.        ]
 [-0.17034316 -0.75248617 -0.6361979   1.        ]
 [-0.94331888 -0.22885131 -0.24036758  1.        ]
 [-0.72251207  0.68825183  0.06546552  1.        ]
 [ 0.16534161 -0.69806294 -0.69668521  1.        ]
 [-0.85577833 -0.45132959  0.25287357  1.        ]
 [-0.12632237 -0.84576684  0.51838318  1.        ]
 [-0.87985926  0.19439549 -0.43365664  1.        ]] [-15714.81481287  74763.64172477 -50751.8768666   23546.15423999
 -33257.42087492  -7457.76401921 -39332.44156406  49633.50169337
  -1428.97952047]
dx ve residuals:  [3.45650269e-06 1.11984621e-07 3.48408679e-06 2.78785437e-06] [1.41409736e+10]
P2 çözümü
Alıcı koordinatları [m]: [3954383.34949925 2278488.87102183 4024981.10696318]
Alıcı saat hatası [s]: -0.0005327764103474858
Alıcı saat hatası [ns]: -532776.4103474858
Kalıntılar [m]: [-15714.81481178  74763.64172668 -50751.8768665   23546.15424132
 -33257.42087552  -7457.76402007 -39332.44156472  49633.50168931
  -1428.97951873]

In [26]:
Q_P1

array([[1.38832353, 0.581102  , 0.41663243, 0.90750373],
       [0.581102  , 0.63379166, 0.29186909, 0.47053069],
       [0.41663243, 0.29186909, 0.71879127, 0.46417491],
       [0.90750373, 0.47053069, 0.46417491, 0.77386549]])

In [27]:
Q_P2

array([[1.38832463, 0.58110242, 0.41663265, 0.90750466],
       [0.58110242, 0.63379184, 0.2918691 , 0.47053101],
       [0.41663265, 0.2918691 , 0.71879133, 0.46417502],
       [0.90750466, 0.47053101, 0.46417502, 0.77386617]])

In [28]:
v_P1

array([-15718.95163169,  74761.04730509, -50765.22302055,  23550.48422196,
       -33255.05019516,  -7442.45180314, -39328.88500785,  49628.09061915,
        -1429.06048782])

In [29]:
v_P2

array([-15714.81481178,  74763.64172668, -50751.8768665 ,  23546.15424132,
       -33257.42087552,  -7457.76402007, -39332.44156472,  49633.50168931,
        -1428.97951873])

### **dop çıktı**

In [30]:
def calculate_dops(Q):
    GDOP = np.sqrt(np.trace(Q))
    PDOP = np.sqrt(np.trace(Q[:3, :3]))
    TDOP = np.sqrt(Q[3, 3])
    return GDOP, PDOP, TDOP

GDOP_P1, PDOP_P1, TDOP_P1 = calculate_dops(Q_P1)
GDOP_P2, PDOP_P2, TDOP_P2 = calculate_dops(Q_P2)

print("       P1       P2")
print(f"GDOP  {GDOP_P1:.4f}   {GDOP_P2:.4f}")
print(f"PDOP  {PDOP_P1:.4f}   {PDOP_P2:.4f}")
print(f"TDOP  {TDOP_P1:.4f}   {TDOP_P2:.4f}")

       P1       P2
GDOP  1.8748   1.8748
PDOP  1.6556   1.6556
TDOP  0.8797   0.8797

### **filter g31**

In [31]:
# G31 dışlanıyor kötü ölçüm
sat_xyz_array_filtered = np.delete(sat_xyz_array, -2, axis=0)

In [32]:
sat_xyz_array_filtered

array([[ 13476921.598, -10426955.243,  20291904.644],
       [ 16469526.655,  -2836172.328,  20153200.739],
       [  7630518.742,  18517714.593,  17754617.164],
       [ 24070866.651,   7158793.606,   9150872.837],
       [ 21867317.358, -14785045.52 ,   2401922.252],
       [   232378.327,  17992583.515,  19708061.664],
       [ 23397361.903,  12532536.308,  -1720216.341],
       [ 22686205.155,  -1860106.849,  13257342.82 ]])

In [33]:
df_filtered = df[df["Satellite"] != "G31"].reset_index(drop=True)

In [34]:
df_filtered

,Satellite,C1,P1,L1,D1,P2,L2,D2
0,G01,2.255605e+07,2.255604e+07,-1.514390e+07,2922.988,2.255604e+07,-1.177665e+07,2277.661
1,G11,2.096043e+07,2.096043e+07,-2.023690e+07,2125.069,2.096042e+07,-1.575303e+07,1655.895
2,G14,2.137030e+07,2.137029e+07,-1.900141e+07,-529.566,2.137029e+07,-1.455393e+07,-412.656
3,G19,2.118906e+07,2.118905e+07,-2.342237e+07,-1624.826,2.118904e+07,-1.823279e+07,-1266.095
4,G20,2.459961e+07,2.459960e+07,-4.001554e+06,3287.044,2.459959e+07,-2.858091e+06,2561.330
5,G22,2.234385e+07,2.234385e+07,-1.900831e+07,-2218.107,2.234382e+07,-1.478600e+07,-1728.398
6,G27,2.252061e+07,2.252059e+07,-1.626506e+07,-3131.943,2.252059e+07,-1.266448e+07,-2440.473
7,G32,2.112843e+07,2.112842e+07,-1.989570e+07,1824.349,2.112841e+07,-1.548879e+07,1421.562

In [35]:
# eski sat1 sat2 silindi yenilendi burada !!!!!!!
for i in range(8):
    globals()[f"sat{i+1}"] = ([str(df_filtered.iloc[i, 0])] + [float(x) for x in df_filtered.iloc[i, 1:]])
    print(globals()[f"sat{i+1}"])

['G01', 22556048.986, 22556038.04462001, -15143902.884, 2922.988, 22556035.42729401, -11776649.861, 2277.661]
['G11', 20960433.392, 20960425.14970588, -20236898.563, 2125.069, 20960421.774224665, -15753030.25, 1655.895]
['G14', 21370295.018, 21370286.18971318, -19001406.309, -529.566, 21370288.72879227, -14553929.347, -412.656]
['G19', 21189058.919, 21189051.21103306, -23422371.335, -1624.826, 21189044.57144488, -18232789.099, -1266.095]
['G20', 24599610.601, 24599598.41016102, -4001554.056, 3287.044, 24599594.33452711, -2858090.765, 2561.33]
['G22', 22343853.992, 22343848.59559468, -19008308.324, -2218.107, 22343819.58930088, -14786004.908, -1728.398]
['G27', 22520607.109, 22520594.159697726, -16265062.308, -3131.943, 22520588.638844248, -12664483.164, -2440.473]
['G32', 21128427.864, 21128417.40142765, -19895704.4, 1824.349, 21128414.788728934, -15488787.194, 1421.562]

In [36]:
P1_corr = []
for i in range(8):
    P1 = globals()[f"sat{i+1}"][2]
    P1_corr.append(P1)

In [37]:
P2_corr = []
for i in range(8):
    P2 = globals()[f"sat{i+1}"][5]
    P2_corr.append(P2)

### **filtered data p1 p2**

In [38]:
X_P1, dt_P1, Q_P1, v_P1 = spp_lsq(
    P=P1_corr,
    sat_coords=sat_xyz_array_filtered,
    rec_init=rec_init
)

print("P1 çözümü")
print("Alıcı koordinatları [m]:", X_P1)
print("Alıcı saat hatası [s]:", dt_P1)
print("Alıcı saat hatası [ns]:", dt_P1 * 1e9)
print("Kalıntılar [m]:", v_P1)

ITERASYON ve A ve l :  0 [[-0.41094783  0.56585937 -0.71479022  1.        ]
 [-0.58956126  0.24865102 -0.76849867  1.        ]
 [-0.15986747 -0.75609268 -0.63463867  1.        ]
 [-0.94413494 -0.22930445 -0.23670381  1.        ]
 [-0.71612055  0.69427858  0.07175384  1.        ]
 [ 0.17741259 -0.6985823  -0.69318652  1.        ]
 [-0.85227488 -0.45293886  0.26167523  1.        ]
 [-0.87930909  0.19963139 -0.43239199  1.        ]] [  3074.89304687 164119.03412554 -32994.94706503 151765.53520535
 -58941.27775311 -69735.68930579   6107.18643169 114902.32027721]
dx ve residuals:  [-329732.38771051  -57942.22958659 -236684.95491168 -241730.13996754] [5.55088274e+09]
ITERASYON ve A ve l :  1 [[-0.42046071  0.55652985 -0.7165803   1.        ]
 [-0.59503708  0.24164963 -0.76650919  1.        ]
 [-0.17325586 -0.75006646 -0.63826539  1.        ]
 [-0.9427278  -0.22792898 -0.24354192  1.        ]
 [-0.7241577   0.68686871  0.0617008   1.        ]
 [ 0.16162472 -0.69652782 -0.69908972  1.        ]
 [-0.85748621 -0.45055543  0.24842946  1.        ]
 [-0.87905176  0.19336574 -0.43574958  1.        ]] [-29153.57268513  43089.35591824 -40473.56257494  12330.94088174
   1132.38129747  22696.16442041    134.44149912 -24619.08204706]
dx ve residuals:  [-3665.29555283  -534.4389956  -2518.28787456 -4921.65975981] [5.58478646e+09]
ITERASYON ve A ve l :  2 [[-0.42056511  0.55643213 -0.71659492  1.        ]
 [-0.5950983   0.2415789  -0.76648395  1.        ]
 [-0.17340397 -0.74999958 -0.63830376  1.        ]
 [-0.94271449 -0.22790934 -0.24361183  1.        ]
 [-0.7242431   0.68678825  0.06159414  1.        ]
 [ 0.16145125 -0.69650395 -0.69915359  1.        ]
 [-0.85754332 -0.45052431  0.24828874  1.        ]
 [-0.87904985  0.19330267 -0.43578141  1.        ]] [-27280.38578017  44028.78578386 -38195.43940903  13062.04342762
   3921.94653603  26077.07377449   2297.70982445 -23913.46091951]
dx ve residuals:  [1.57897484 0.1023718  1.36163465 1.20742001] [5.58479052e+09]
ITERASYON ve A ve l :  3 [[-0.42056507  0.55643217 -0.71659491  1.        ]
 [-0.59509828  0.24157893 -0.76648396  1.        ]
 [-0.17340391 -0.74999962 -0.63830374  1.        ]
 [-0.9427145  -0.22790936 -0.24361179  1.        ]
 [-0.72424306  0.68678828  0.06159419  1.        ]
 [ 0.16145132 -0.69650397 -0.69915356  1.        ]
 [-0.85754329 -0.45052433  0.24828881  1.        ]
 [-0.87904986  0.19330269 -0.43578139  1.        ]] [-27280.01036098  44029.53694932 -38195.42711327  13062.67957186
   3921.72850112  26076.63472106   2297.56448613 -23912.70675561]
dx ve residuals:  [-0.00101482 -0.00013108 -0.00087654 -0.00091899] [5.58479052e+09]
ITERASYON ve A ve l :  4 [[-0.42056507  0.55643217 -0.71659491  1.        ]
 [-0.59509828  0.24157893 -0.76648396  1.        ]
 [-0.17340391 -0.74999962 -0.63830374  1.        ]
 [-0.9427145  -0.22790936 -0.24361179  1.        ]
 [-0.72424306  0.68678828  0.06159419  1.        ]
 [ 0.16145132 -0.69650397 -0.69915356  1.        ]
 [-0.85754329 -0.45052433  0.24828881  1.        ]
 [-0.87904986  0.19330269 -0.43578139  1.        ]] [-27280.01042396  44029.53662422 -38195.42702806  13062.67929076
   3921.72882916  26076.63509976   2297.56469346 -23912.70708533]
dx ve residuals:  [6.09266699e-07 5.24826469e-08 5.39297025e-07 5.54988775e-07] [5.58479052e+09]
P1 çözümü
Alıcı koordinatları [m]: [3875434.2007973  2276373.73285858 3932065.36687241]
Alıcı saat hatası [s]: -0.0008227378195944415
Alıcı saat hatası [ns]: -822737.8195944414
Kalıntılar [m]: [-27280.01042391  44029.53662442 -38195.42702813  13062.67929092
   3921.72882898  26076.63509952   2297.56469331 -23912.70708513]

In [39]:
X_P2, dt_P2, Q_P2, v_P2 = spp_lsq(
    P=P2_corr,
    sat_coords=sat_xyz_array_filtered,
    rec_init=rec_init
)

print("P2 çözümü")
print("Alıcı koordinatları [m]:", X_P2)
print("Alıcı saat hatası [s]:", dt_P2)
print("Alıcı saat hatası [ns]:", dt_P2 * 1e9)
print("Kalıntılar [m]:", v_P2)

ITERASYON ve A ve l :  0 [[-0.41094783  0.56585937 -0.71479022  1.        ]
 [-0.58956126  0.24865102 -0.76849867  1.        ]
 [-0.15986747 -0.75609268 -0.63463867  1.        ]
 [-0.94413494 -0.22930445 -0.23670381  1.        ]
 [-0.71612055  0.69427858  0.07175384  1.        ]
 [ 0.17741259 -0.6985823  -0.69318652  1.        ]
 [-0.85227488 -0.45293886  0.26167523  1.        ]
 [-0.87930909  0.19963139 -0.43239199  1.        ]] [  3072.27572087 164115.65864433 -32992.40798594 151758.89561717
 -58945.35338702 -69764.69559959   6101.66557821 114899.7075785 ]
dx ve residuals:  [-329749.00222569  -57940.75826926 -236691.98085152 -241748.32405132] [5.54892546e+09]
ITERASYON ve A ve l :  1 [[-0.4204612   0.5565296  -0.7165802   1.        ]
 [-0.59503742  0.24164952 -0.76650895  1.        ]
 [-0.17325658 -0.75006618 -0.63826553  1.        ]
 [-0.94272783 -0.22792873 -0.24354205  1.        ]
 [-0.72415801  0.68686842  0.06170049  1.        ]
 [ 0.16162398 -0.69652772 -0.69909     1.        ]
 [-0.8574865  -0.45055513  0.24842903  1.        ]
 [-0.8790518   0.19336565 -0.43574954  1.        ]] [-29150.84516379  43088.53727556 -40459.09880934  12325.44665601
   1133.88111905  22684.14057064    135.26636808 -24621.46173362]
dx ve residuals:  [-3665.72862786  -534.45599074 -2518.5189785  -4922.14438098] [5.58281984e+09]
ITERASYON ve A ve l :  2 [[-0.42056562  0.55643187 -0.71659482  1.        ]
 [-0.59509866  0.24157879 -0.76648371  1.        ]
 [-0.17340471 -0.74999929 -0.63830391  1.        ]
 [-0.94271451 -0.22790909 -0.24361197  1.        ]
 [-0.72424341  0.68678795  0.06159381  1.        ]
 [ 0.16145048 -0.69650384 -0.69915387  1.        ]
 [-0.85754361 -0.45052401  0.24828829  1.        ]
 [-0.87904989  0.19330257 -0.43578137  1.        ]] [-27277.51361893  44028.0202724  -38180.72920915  13056.56508506
   3923.64118391  26065.42768563   2298.69567426 -23915.83420418]
dx ve residuals:  [1.57823296 0.1023304  1.36145082 1.20688813] [5.5828239e+09]
ITERASYON ve A ve l :  3 [[-0.42056558  0.55643191 -0.71659481  1.        ]
 [-0.59509864  0.24157882 -0.76648372  1.        ]
 [-0.17340464 -0.74999932 -0.63830388  1.        ]
 [-0.94271452 -0.2279091  -0.24361193  1.        ]
 [-0.72424337  0.68678798  0.06159387  1.        ]
 [ 0.16145056 -0.69650386 -0.69915384  1.        ]
 [-0.85754358 -0.45052403  0.24828836  1.        ]
 [-0.8790499   0.19330259 -0.43578135  1.        ]] [-27277.13808788  44028.77139759 -38180.71665723  13057.20100777
   3923.42318429  26064.98912807   2298.55025964 -23915.08023264]
dx ve residuals:  [-0.00101403 -0.00013098 -0.00087615 -0.0009184 ] [5.5828239e+09]
ITERASYON ve A ve l :  4 [[-0.42056558  0.55643191 -0.71659481  1.        ]
 [-0.59509864  0.24157882 -0.76648372  1.        ]
 [-0.17340464 -0.74999932 -0.63830388  1.        ]
 [-0.94271452 -0.2279091  -0.24361193  1.        ]
 [-0.72424337  0.68678798  0.06159387  1.        ]
 [ 0.16145056 -0.69650386 -0.69915384  1.        ]
 [-0.85754358 -0.45052403  0.24828836  1.        ]
 [-0.8790499   0.19330259 -0.43578135  1.        ]] [-27277.13815091  44028.77107263 -38180.71657215  13057.20072694
   3923.42351221  26064.98950639   2298.550467   -23915.08056212]
dx ve residuals:  [6.06928310e-07 5.25539084e-08 5.34749405e-07 5.51122001e-07] [5.5828239e+09]
P2 çözümü
Alıcı koordinatları [m]: [3875417.15246598 2276375.18713947 3932058.10964518]
Alıcı saat hatası [s]: -0.0008228000934633713
Alıcı saat hatası [ns]: -822800.0934633713
Kalıntılar [m]: [-27277.13815085  44028.77107284 -38180.71657222  13057.2007271
   3923.42351203  26064.98950616   2298.55046686 -23915.08056191]

### **uydu saat hatası**

In [40]:
sat_clk_list_filtered = []
for i in sat_xyz_list:
    if i[0] in satellites:
        sat_clk_list_filtered.append(float(i[4]))

In [41]:
sat_clk_array_filtered = np.delete(
    np.array(sat_clk_list_filtered),
    -2
)

In [42]:
sat_clk_array_filtered

array([  20.349088, -516.907462,  140.375953, -475.879466,  227.296058,
        262.830139,    9.874415, -352.739025])

In [43]:
P1_corr = np.asarray(P1_corr, dtype=float)
P2_corr = np.asarray(P2_corr, dtype=float)

P1_corr = P1_corr + c * sat_clk_array_filtered * 1e-6
P2_corr = P2_corr + c * sat_clk_array_filtered * 1e-6

In [44]:
P1_corr

array([22562138.54772959, 20805460.19111436, 21412369.84170714,
       21046386.13620919, 24667740.05408255, 22422643.08900197,
       22523554.43484189, 21022668.90209037])

In [45]:
P2_corr

array([22562135.93040359, 20805456.81563314, 21412372.38078623,
       21046379.49662101, 24667735.97844864, 22422614.08270817,
       22523548.91398841, 21022666.28939166])

### **sat clock düzeltilmiş filtrelenmiş p1 p2 hesap**

In [46]:
X_P1, dt_P1, Q_P1, v_P1 = spp_lsq(
    P=P1_corr,
    sat_coords=sat_xyz_array_filtered,
    rec_init=rec_init
)

print("P1 çözümü")
print("Alıcı koordinatları [m]:", X_P1)
print("Alıcı saat hatası [s]:", dt_P1)
print("Kalıntılar [m]:", v_P1)

ITERASYON ve A ve l :  0 [[-0.41094783  0.56585937 -0.71479022  1.        ]
 [-0.58956126  0.24865102 -0.76849867  1.        ]
 [-0.15986747 -0.75609268 -0.63463867  1.        ]
 [-0.94413494 -0.22930445 -0.23670381  1.        ]
 [-0.71612055  0.69427858  0.07175384  1.        ]
 [ 0.17741259 -0.6985823  -0.69318652  1.        ]
 [-0.85227488 -0.45293886  0.26167523  1.        ]
 [-0.87930909  0.19963139 -0.43239199  1.        ]] [9175.39615645 9154.07553402 9088.70492893 9100.46038148 9200.36616842
 9058.8041015  9067.46157585 9153.82093994]
dx ve residuals:  [ 3.59185167e+00  9.22582120e+01 -1.20994748e+01  9.12703269e+03] [1245.27496177]
ITERASYON ve A ve l :  1 [[-0.41094659  0.56586197 -0.71478887  1.        ]
 [-0.58956023  0.24865509 -0.76849813  1.        ]
 [-0.15986777 -0.75609059 -0.63464109  1.        ]
 [-0.94413574 -0.2293003  -0.23670463  1.        ]
 [-0.71611865  0.69428061  0.07175318  1.        ]
 [ 0.17741319 -0.69857991 -0.69318877  1.        ]
 [-0.85227653 -0.45293573  0.26167525  1.        ]
 [-0.87930806  0.19963558 -0.43239214  1.        ]] [-11.01434035  -3.07825075  24.32331647  -4.89007997  12.72086333
 -12.80318856 -11.55654492   6.29705433]
dx ve residuals:  [ 1.01599130e-04  1.79150071e-05  2.06786911e-05 -8.16498409e-05] [1245.27655174]
ITERASYON ve A ve l :  2 [[-0.41094659  0.56586197 -0.71478887  1.        ]
 [-0.58956023  0.24865509 -0.76849813  1.        ]
 [-0.15986777 -0.75609059 -0.63464109  1.        ]
 [-0.94413574 -0.2293003  -0.23670463  1.        ]
 [-0.71611865  0.69428061  0.07175318  1.        ]
 [ 0.17741319 -0.69857991 -0.69318877  1.        ]
 [-0.85227653 -0.45293573  0.26167525  1.        ]
 [-0.87930806  0.19963558 -0.43239214  1.        ]] [-11.0142123   -3.07809776  24.32344103  -4.88989339  12.72100381
 -12.80309808 -11.55637398   6.29723068]
dx ve residuals:  [ 8.61567720e-10  5.86460242e-10 -2.85293124e-09 -6.66929726e-10] [1245.27655165]
P1 çözümü
Alıcı koordinatları [m]: [4208833.89805327 2334942.55742988 4171255.14944584]
Alıcı saat hatası [s]: 3.044450372635692e-05
Kalıntılar [m]: [-11.0142123   -3.07809776  24.32344103  -4.88989339  12.72100381
 -12.80309808 -11.55637398   6.29723068]

In [47]:
X_P2, dt_P2, Q_P2, v_P2 = spp_lsq(
    P=P2_corr,
    sat_coords=sat_xyz_array_filtered,
    rec_init=rec_init
)

print("P2 çözümü")
print("Alıcı koordinatları [m]:", X_P2)
print("Alıcı saat hatası [s]:", dt_P2)
print("Kalıntılar [m]:", v_P2)

ITERASYON ve A ve l :  0 [[-0.41094783  0.56585937 -0.71479022  1.        ]
 [-0.58956126  0.24865102 -0.76849867  1.        ]
 [-0.15986747 -0.75609268 -0.63463867  1.        ]
 [-0.94413494 -0.22930445 -0.23670381  1.        ]
 [-0.71612055  0.69427858  0.07175384  1.        ]
 [ 0.17741259 -0.6985823  -0.69318652  1.        ]
 [-0.85227488 -0.45293886  0.26167523  1.        ]
 [-0.87930909  0.19963139 -0.43239199  1.        ]] [9172.77883045 9150.70005281 9091.24400802 9093.8207933  9196.29053451
 9029.7978077  9061.94072238 9151.20824122]
dx ve residuals:  [ -13.02266352   93.72952929  -19.12541468 9108.84860259] [2648.16678337]
ITERASYON ve A ve l :  1 [[-0.4109471   0.56586172 -0.71478878  1.        ]
 [-0.58956059  0.24865498 -0.7684979   1.        ]
 [-0.1598685  -0.75609031 -0.63464125  1.        ]
 [-0.94413576 -0.22930005 -0.23670477  1.        ]
 [-0.71611896  0.69428032  0.07175286  1.        ]
 [ 0.17741244 -0.69857982 -0.69318906  1.        ]
 [-0.85227683 -0.45293543  0.2616748   1.        ]
 [-0.8793081   0.19963548 -0.43239211  1.        ]] [ -8.12989075  -3.83017982  39.04384603 -10.35764177  14.41397197
 -24.52024167 -10.54855354   3.92747362]
dx ve residuals:  [ 8.18926980e-05  4.50350931e-05 -1.19332980e-05 -1.09489572e-04] [2648.1699271]
P2 çözümü
Alıcı koordinatları [m]: [4208817.28351838 2334944.02877433 4171248.12347338]
Alıcı saat hatası [s]: 3.0383848058966856e-05
Kalıntılar [m]: [ -8.12978162  -3.83004242  39.04399509 -10.35744746  14.41410969
 -24.52012352 -10.54835074   3.92764097]

In [48]:
X_P1 - rec_init

array([  3.59195327,  92.25822988, -12.09945416])

In [49]:
X_P2 - rec_init

array([-13.02258162,  93.72957433, -19.12542662])

In [50]:
Q_P1

array([[2.04333876, 0.58296618, 1.22552929, 1.63068276],
       [0.58296618, 0.62312595, 0.30702195, 0.4729357 ],
       [1.22552929, 0.30702195, 1.67919134, 1.34713139],
       [1.63068276, 0.4729357 , 1.34713139, 1.57196063]])

In [51]:
Q_P2

array([[2.04334311, 0.58296712, 1.22553207, 1.63068719],
       [0.58296712, 0.62312651, 0.30702226, 0.47293661],
       [1.22553207, 0.30702226, 1.67919398, 1.34713464],
       [1.63068719, 0.47293661, 1.34713464, 1.57196514]])

In [52]:
v_P1

array([-11.0142123 ,  -3.07809776,  24.32344103,  -4.88989339,
        12.72100381, -12.80309808, -11.55637398,   6.29723068])

In [53]:
v_P2

array([ -8.12978162,  -3.83004242,  39.04399509, -10.35744746,
        14.41410969, -24.52012352, -10.54835074,   3.92764097])

In [54]:
# son durum dops hesabı
def calculate_dops(Q):
    GDOP = np.sqrt(np.trace(Q))
    PDOP = np.sqrt(np.trace(Q[:3, :3]))
    TDOP = np.sqrt(Q[3, 3])
    return GDOP, PDOP, TDOP

GDOP_P1, PDOP_P1, TDOP_P1 = calculate_dops(Q_P1)
GDOP_P2, PDOP_P2, TDOP_P2 = calculate_dops(Q_P2)

print("       P1       P2")
print(f"GDOP  {GDOP_P1:.4f}   {GDOP_P2:.4f}")
print(f"PDOP  {PDOP_P1:.4f}   {PDOP_P2:.4f}")
print(f"TDOP  {TDOP_P1:.4f}   {TDOP_P2:.4f}")

       P1       P2
GDOP  2.4326   2.4326
PDOP  2.0846   2.0846
TDOP  1.2538   1.2538

In [55]:
len(P1_corr)

8